name: Rafael Souza
url: http://rafaelss.com
description: A blog.
gravatar_url: http://www.gravatar.com/avatar/ac6913d397fb6db22333d48d46a24812
github: rafaelss
twitter: rafaelss
safe: true
auto: true
server: thin
markdown: kramdown
pygments: true
future: false
permalink: /:year/:month/:day/:title
paginate: 20
